apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "chart-template.labels" . | nindent 4 }}
  name: zesty-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
