allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zesty-sc
parameters:
  csi.storage.k8s.io/fstype: btrfs
  fsType: btrfs
provisioner: storage.zesty.co
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
