apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
data:
  defaultStorageClassProvisioner: ebs.csi.aws.com
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  cascadeAnnotations.excludedValues: |
    - kubernetes.io
    - k8s.io
  cascadeLabels.excludedValues: |
    - elastic.co