apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "labels" . | nindent 4 }}
  name: {{ include "admission.mutator.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8443
    targetPort: {{ .Values.admission.mutator.port }}
  selector:
    app: {{ include "admission.mutator.name" . }}
