apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "extender.name" . }}
  namespace: kube-system
data:
  scheduler-extender-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: {{ include "scheduler.name" . }}
    leaderElection:
      leaderElect: true
    extenders:
      - urlPrefix: "http://localhost:{{ .Values.extender.port }}"
        filterVerb: filter
        weight: 1
        enableHTTPS: false
        httpTimeout: 1m
