apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zestyStorageAgent.name" . }}
rules:
  - apiGroups: ["", "apps/v1"]
    resources: ["persistentvolumeclaims", "persistentvolumes", "events", "nodes", "statefulsets"]
    verbs: ["get", "watch", "list", "patch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  - apiGroups: ["storage.k8s.io" ]
    resources: ["volumeattachments"]
    verbs: [ "get", "list", "patch", "update"]
  - apiGroups: ["storage.k8s.io" ]
    resources: ["storageclasses" ]
    verbs: [ "get", "list"]
  - apiGroups: ["storage.zesty.co" ]
    resources: ["filesystems" ]
    verbs: [ "get", "list", "patch", "update" ]
