apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "zestyStorageAgent.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "zestyStorageAgent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "zestyStorageAgent.name" . }}
      {{- if .Values.zestyStorageAgent.prometheusExporter.port }}
      annotations:
        prometheus.io/port: {{ .Values.zestyStorageAgent.prometheusExporter.port | quote}}
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.zestyStorageAgent.priorityClassName | default "system-node-critical" }}
      hostPID: true
      containers:
        - name: agent
          image: {{ include "agent.image" . }}:{{ .Values.zestyStorageAgent.agent.image.tag }}
          imagePullPolicy: Always
{{- with .Values.zestyStorageAgent.agent.resources }}
          resources:
{{- toYaml . | nindent 12 }}
{{- end }}
          volumeMounts:
            - name: host-path-mnt
              mountPath: /mnt
            - name: host-path-dev
              mountPath: /dev
            - name: shared
              mountPath: /host
          securityContext:
            privileged: true
          env:
            - name: ZESTY_BASE_URL
              value: {{ .Values.zestyStorageAgent.baseUrl | quote }}
          {{- if ne .Values.zestyStorageAgent.apiKey ""}}   
            - name: ZESTY_API_KEY
              value: {{ .Values.zestyStorageAgent.apiKey | quote }}
          {{- end }}
          {{- if eq .Values.zestyStorageAgent.apiKey "" }}
          envFrom:
          - secretRef:
                name: {{ .Values.zestyStorageAgent.secret.name | quote }}
           {{- end }}
        - name: manager
          image: {{ include "manager.image" . }}:{{ .Values.zestyStorageAgent.manager.image.tag }}
          imagePullPolicy: Always
{{- with .Values.zestyStorageAgent.manager.resources }}
          resources:
{{- toYaml . | nindent 12 }}
{{- end }}
        {{- if .Values.zestyStorageAgent.prometheusExporter.port }}
        - name: prometheus-exporter
          image: {{ include "prometheusExporter.image" . }}:{{ .Values.zestyStorageAgent.prometheusExporter.image.tag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: shared
              mountPath: /host
          env:
            - name: PROMETHEUS_EXPORTER_PORT
              value: {{ .Values.zestyStorageAgent.prometheusExporter.port | quote }}
          ports:
            - containerPort: {{ .Values.zestyStorageAgent.prometheusExporter.port }}
        {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: host-path-mnt
          hostPath:
            path: /mnt
        - name: host-path-dev
          hostPath:
            path: /dev
        - name: shared
          emptyDir: {}
