apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "chart-template.labels" . | nindent 4 }}
  name: {{ include "chart-template.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}