apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  defaultStorageClassProvisioner: ebs.csi.aws.com
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}